(include "led-images/led-image-bell.scm")
(include "led-images/led-image-black.scm")
(include "led-images/led-image-key.scm")
(include "led-images/led-image-didring-1.scm")
(include "led-images/led-image-didring-2.scm")
(include "led-images/led-image-didring-3.scm")
(include "led-images/led-image-didring-4.scm")
