;;;; linphone.import.scm - GENERATED BY CHICKEN 4.12.0 -*- Scheme -*-

(eval '(import chicken scheme foreign posix))
(##sys#register-compiled-module
  'linphone
  (list)
  '((i2c-close . linphone#i2c-close)
    (i2c-open . linphone#i2c-open)
    (i2c-set-slave-addr . linphone#i2c-set-slave-addr)
    (linphone_core_new . linphone#linphone_core_new)
    (linphone-berit . linphone#linphone-berit))
  (list)
  (list))

;; END OF FILE
